-- begin CONTACTBASE_ACCESS_REQUEST_REGION_LINK
alter table CONTACTBASE_ACCESS_REQUEST_REGION_LINK add constraint FK_ACCREQREG_ACCESS_REQUEST foreign key (ACCESS_REQUEST_ID) references CONTACTBASE_ACCESS_REQUEST(ID)^
alter table CONTACTBASE_ACCESS_REQUEST_REGION_LINK add constraint FK_ACCREQREG_REGION foreign key (REGION_ID) references CONTACTBASE_REGION(ID)^
-- end CONTACTBASE_ACCESS_REQUEST_REGION_LINK
